Only refill captchas when use-captcha? is truthy
Fixes error in tests:

Error: (call-with-input-request) Server error: 500 Internal server error:
  #<URI-common: scheme=http port=8080 host="localhost" path=(/ "paste") query=() fragment=#f>

The error was not showing up because of a bug in server-test (it was
not propagating exceptions).

Signed-off-by: Christian Kellermann <ckeen@pestilenz.org>